### ISSUE TITLE
R_MatrixMultiply can be more efficient

### ISSUE THREAD

**Issue by IJzerbaard** [TheRealMHMH/DirectQII#1]
Current approach of R_MatrixMultiply requires a transpose (8 shuffles) and 12 horizontal additions (2 shuffles each), the effective cost is 32 shuffles plus arithmetic. The computation can also be arranged as 16 broadcasts (16 shuffles in SSE, zero shuffles with AVX) plus an equal amount of computation. For example like [this](https://stackoverflow.com/a/18508113/555045).

**Comment by mhQuake** [comment]
Resolved
