### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by ghost** [TheRealMHMH/DirectQII#2]
Hey could you possibly add build instructions? I know I need Visual Studio but have no idea which version to use. Everything from VS 2010 and up gets build errors. Also couldn't find VS 2008 anywhere, the only thing still available on Microsoft's site is the SP1 update for it.

**Comment by mhQuake** [comment]
It's a 2008 SP1 project so it builds best with 2008 SP1, but you'll also need a DirectX SDK.  I'll lift it to 2013 which should be better.
