### ISSUE TITLE
Latest Code Slow Performance

### ISSUE THREAD

**Issue by gribbs88** [TheRealMHMH/DirectQII#5]
Just built your latest code and it runs very poorly when starting a multiplayer server. The game runs as normal if just loading a map through the console, but once a map is loaded through the main menu it runs like it's at 25fps, yet timerefresh shows high framerates. If I load a map through the console after that, the extreme laggy feel is still there.

**Comment by mhQuake** [comment]
I don't recommend using this engine as a server - I haven't done any real work on that side of it.  Use a different engine instead, and connect to it using this engine.

**Comment by gribbs88** [comment]
Ach! I should have said multiplayer game! Sorry, not server.
